---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-apps-ext-not-istio

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ext-not-istio
  namespace: nginx-apps-ext-not-istio
spec:
  selector:
    matchLabels:
      app: nginx-ext-not-istio
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ext-not-istio
    spec:
      containers:
       - name: nginx-ext-not-istio
         image: nginx:1.14
         ports:
           - containerPort: 80

---

apiVersion: v1
kind: Service

metadata:
  name: lb-nginx-service
  namespace: nginx-apps-ext-not-istio
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer

  selector:
    app: nginx-ext-not-istio
  ports:
     - name: http
       port: 80
       targetPort: 80
       protocol: TCP

# ---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: nginx-apps-ext-not-istio
spec:
  rules:
   - host: mydomain.com
     http:
       paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: lb-nginx-service
              port:
                number: 80
